name: CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up vcpkg
      run: |
        sudo apt update
        sudo apt install -y cmake
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh

    - name: Build application
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build build

    - name: Build unit tests
      run: |
        cd unit_test
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build build

    - name: Run unit tests
      run: |
        cd unit_test
        ./build/unit_tests