name: CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup dependencies
      run: |
        sudo apt update
        sudo apt install -y libboost-program-options-dev
        mkdir thirdparty
        cd thirdparty
        git clone https://github.com/microsoft/compoundfilereader.git
        cd -
    - name: Build application
      run: |
        mkdir build
        cmake -B build
        cmake --build build